trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: PlaywrightPom   # alias
      type: github
      name: nnatikar/PlaywrightPom      # GitHub path
      endpoint: nnatikar # service connection name

steps:
- checkout: self
- checkout: PlaywrightPom

# Install dependencies & run Playwright tests
- script: |
    npm install
    npx playwright install --with-deps
    npx playwright test
  workingDirectory: "PlaywrightPom"
  displayName: 'Execute Playwright Project'